Resources:
  PatientTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: PatientTable-${self:provider.environment.STAGE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

      StreamSpecification:
        StreamViewType: NEW_IMAGE
